In [76]:
import numpy as np
import random
#Решите без использования циклов средставми NumPy (каждый пункт решается в 1-2 строчки)

In [8]:
# 1. Создайте вектор с элементами от 12 до 42
np.arange(12,43)

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42])

In [15]:
# 2. Создайте вектор из нулей длины 12, но его пятый элемент(индекс=4) должен быть равен 1
vc = np.array([0] * 12)
vc[4] = 1
vc

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0])

In [97]:
# 3. Создайте матрицу (3, 3), заполненую от 0 до 8
matrix = np.arange(9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [72]:
# 4. Найдите все положительные числа в массиве, например в np.array([1,2,0,0,4,0])
mx = np.array([1,2,0,0,4,0])
mx[mx > 0]

array([1, 2, 4])

In [75]:
# 5. Умножьте матрицу размерности (5, 3) на (3, 2)
mx1 = np.arange(15).reshape(5,3)
mx2 = np.arange(6).reshape(3,2)
mx3 = np.dot(mx1, mx2)
mx1, mx2, mx3

(array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]]),
 array([[0, 1],
        [2, 3],
        [4, 5]]),
 array([[ 10,  13],
        [ 28,  40],
        [ 46,  67],
        [ 64,  94],
        [ 82, 121]]))

In [70]:
# 6. Создайте матрицу (10, 10) так, чтобы на границе были 0, а внутри 1
mx = np.full((10, 10), 0)
mx[1:9, 1:9] = 1
mx

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [89]:
# 7. Создайте рандомный вектор и отсортируйте его
vect = np.random.randint(1, 10, 10)
np.sort(vect)

array([2, 2, 2, 2, 5, 6, 6, 7, 7, 9])

In [95]:
# 8. Каков эквивалент функции enumerate для numpy массивов?
np.ndenumerate(mx)

In [118]:
# 9. *Создайте матрицу(3x3) и выполните нормализацию столбцов
# (из каждого столбца вычесть среднее этого столбца, полученный результат разделить на std этого столбца)
avg = np.average(matrix, axis = 0)
m_matrix = matrix - avg
st = np.std(matrix, axis = 0)
st_matrix = matrix / st
matrix, avg, d_matrix, st, st_matrix

(array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),
 array([3., 4., 5.]),
 array([[-3., -3., -3.],
        [ 0.,  0.,  0.],
        [ 3.,  3.,  3.]]),
 array([2.44948974, 2.44948974, 2.44948974]),
 array([[0.        , 0.40824829, 0.81649658],
        [1.22474487, 1.63299316, 2.04124145],
        [2.44948974, 2.85773803, 3.26598632]]))

In [171]:
# 10. *Для заданного числа найдите ближайший к нему элемент в векторе (подсказка: np.random.randint(qty, size=()), np.random.choice)
vc = np.random.randint(5, size=(10))
number = np.random.choice(5)
ind = np.where(vc == number)[0]
nearest = vc[ind - 1]
number, vc, nearest

(0, array([1, 0, 0, 2, 2, 0, 1, 3, 0, 1]), array([1, 0, 2, 3]))

In [184]:
# 11. *Найдите N наибольших значений в векторе
vec = np.random.randint(10, size=(10))
vec_uniq = set(list(vec))
srt = sorted(vec_uniq)
N = np.random.choice(10)
print(vec, '\n',  srt, '\n', N, '\n', srt[-N:])

[4 2 5 3 0 9 4 9 5 1] 
 [0, 1, 2, 3, 4, 5, 9] 
 6 
 [1, 2, 3, 4, 5, 9]
